language: ruby
sudo: false
cache:
  bundler: true
rvm:
  - 2.3
branches:
  only:
    - master
after_success:
  - npm install -g surge
  - rake hvsc > /dev/null
  - rake index > /dev/null
  - rake deploy > /dev/null
